[project]
name = "tango"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "torch==1.4.0",
  "torch-scatter==2.0.5",
  "torchdiffeq==0.1.0"
]

[tool.uv.extra-build-dependencies]
torch-scatter = ["torch"]